### PR TITLE
feat: support pnpm workspace

### PR DESCRIPTION
**Pull request by liweijie0812**
pnpm 安装，package/scripts 缺少chalk 依赖，运行pnpm api:docs 报错

### CODE REVIEW

**Comment by uyarn** [comment]
https://github.com/TDesignOteam/tdesign-api/blob/main/package.json#L7 这个没用了也删掉吧

**Comment by liweijie0812** [comment]
> https://github.com/TDesignOteam/tdesign-api/blob/main/package.json#L7 这个没用了也删掉吧

ci还是npm安装，还不能删

**Comment by uyarn** [comment]
```
 - uses: pnpm/action-setup@v3
        with:
          version: 8
```
https://github.com/pnpm/action-setup 加下这个step 换成pnpm install呢 一块调整掉咯

**Comment by liweijie0812** [comment]
> ```
>  - uses: pnpm/action-setup@v3
>         with:
>           version: 8
> ```
> 
> https://github.com/pnpm/action-setup 加下这个step 换成pnpm install呢 一块调整掉咯

处理好了

**Review by uyarn — APPROVED** [review]
LGTM

**Pull request merged**
